export const playerData = {
  id: "123456789",
  name: "Faker",
  server: "NA",
  avatar: "https://picsum.photos/seed/avatar/150/150",
  level: 112,
  rank: {
    tier: "Mythic Glory",
    points: 1250,
    icon: "https://picsum.photos/seed/mythic/100/100",
  },
  stats: {
    winRate: 68.5,
    totalMatches: 420,
    wins: 288,
    losses: 132,
    kda: "4.2",
    kills: 8.5,
    deaths: 3.2,
    assists: 5.1,
    mvp: 145,
  },
  topHeroes: [
    {
      id: "ling",
      name: "Ling",
      matches: 120,
      winRate: 72,
      kda: "5.1",
      image: "https://picsum.photos/seed/ling/100/100",
      role: "Assassin",
    },
    {
      id: "lancelot",
      name: "Lancelot",
      matches: 85,
      winRate: 65,
      kda: "4.5",
      image: "https://picsum.photos/seed/lancelot/100/100",
      role: "Assassin",
    },
    {
      id: "chou",
      name: "Chou",
      matches: 64,
      winRate: 60,
      kda: "3.8",
      image: "https://picsum.photos/seed/chou/100/100",
      role: "Fighter",
    },
  ],
  recentMatches: [
    {
      id: "m1",
      result: "Victory",
      hero: { name: "Ling", image: "https://picsum.photos/seed/ling/100/100" },
      kda: "12 / 2 / 8",
      duration: "15:23",
      timeAgo: "2h ago",
      type: "Ranked",
      items: [
        "https://picsum.photos/seed/item1/50/50",
        "https://picsum.photos/seed/item2/50/50",
        "https://picsum.photos/seed/item3/50/50",
        "https://picsum.photos/seed/item4/50/50",
        "https://picsum.photos/seed/item5/50/50",
        "https://picsum.photos/seed/item6/50/50",
      ],
      spells: [
        "https://picsum.photos/seed/retri/50/50",
      ],
      mvp: true,
    },
    {
      id: "m2",
      result: "Defeat",
      hero: { name: "Lancelot", image: "https://picsum.photos/seed/lancelot/100/100" },
      kda: "5 / 6 / 4",
      duration: "21:10",
      timeAgo: "5h ago",
      type: "Ranked",
      items: [
        "https://picsum.photos/seed/item1/50/50",
        "https://picsum.photos/seed/item2/50/50",
        "https://picsum.photos/seed/item3/50/50",
        "https://picsum.photos/seed/item4/50/50",
        null,
        null,
      ],
      spells: [
        "https://picsum.photos/seed/retri/50/50",
      ],
      mvp: false,
    },
    {
      id: "m3",
      result: "Victory",
      hero: { name: "Chou", image: "https://picsum.photos/seed/chou/100/100" },
      kda: "3 / 1 / 15",
      duration: "18:45",
      timeAgo: "1d ago",
      type: "Ranked",
      items: [
        "https://picsum.photos/seed/item7/50/50",
        "https://picsum.photos/seed/item8/50/50",
        "https://picsum.photos/seed/item9/50/50",
        "https://picsum.photos/seed/item10/50/50",
        "https://picsum.photos/seed/item11/50/50",
        "https://picsum.photos/seed/item12/50/50",
      ],
      spells: [
        "https://picsum.photos/seed/flicker/50/50",
      ],
      mvp: false,
    },
    {
      id: "m4",
      result: "Victory",
      hero: { name: "Ling", image: "https://picsum.photos/seed/ling/100/100" },
      kda: "15 / 0 / 5",
      duration: "12:10",
      timeAgo: "1d ago",
      type: "Ranked",
      items: [
        "https://picsum.photos/seed/item1/50/50",
        "https://picsum.photos/seed/item2/50/50",
        "https://picsum.photos/seed/item3/50/50",
        "https://picsum.photos/seed/item4/50/50",
        "https://picsum.photos/seed/item5/50/50",
        null,
      ],
      spells: [
        "https://picsum.photos/seed/retri/50/50",
      ],
      mvp: true,
    },
  ],
};
